### PR TITLE
Fixed some mistakes.

### PR DESCRIPTION
**Pull request by Xackspel**
Hi. I have fixed some mistakes in your .index.html and css files.

All photos in [section portfolio] should have photos with same sizes. Only if all photo in this sction will be have same sizes your webpage will bw looks more better and clean. Sincerely.

### CODE REVIEW

**Comment by osbre** [comment]
wooow, Thank you very much, I test it and merge

**Comment by Xackspel** [comment]
You are welcome!
Нема за що =)))

**Comment by Xackspel** [comment]
In Sunday I will update all photos for your portfolio, and I will upload for your portfolio.

**Comment by osbre** [comment]
wow, thanks friends

**Pull request merged**
